name: LightweightHomes
version: '${project.version}'
main: org.blackninja745studios.lightweighthomes.LightweightHomes
api-version: 1.18
load: STARTUP
authors: [BlackNinja745 Studios]
website: https://bn745studios.com/